app.greeting: Hello

server.port: 8080
server.host: 0.0.0.0

mp:
  messaging:
    connector:
      helidon-jms:
        jndi:
          jms-factory: jms/TestConnectionFactory
          env-properties:
            java.naming.factory.initial: weblogic.jndi.WLInitialContextFactory
            java.naming.provider.url: t3://localhost:7001
    incoming:
      IncomingQueue:
        connector: helidon-jms
        destination: ./TestJMSModule!IncomingQueue
    outgoing:
      OutgoingQueue:
        connector: helidon-jms
        # Same queue is used for simplifying test case
        destination: ./TestJMSModule!IncomingQueue
